# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 15:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=128)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=32)),
                ('cell', models.CharField(default='연락처', max_length=32)),
                ('charge', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=128)),
                ('cctv', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cctv_metas', to='all.Cctv')),
            ],
        ),
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='NeighborAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(default='개체 번호', max_length=128)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now)),
                ('size', models.CharField(default='개체 크기', max_length=128)),
                ('xpos', models.FloatField(default=0.0)),
                ('ypos', models.FloatField(default=0.0)),
                ('speed', models.FloatField(default=0.0)),
                ('color', models.CharField(default='색상', max_length=32)),
                ('meta', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_rows', to='all.Meta')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbors', models.ManyToManyField(blank=True, null=True, related_name='neighbor_seqs', to='all.Neighbor')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indoor_loc', models.CharField(default='주소', max_length=128)),
                ('floor_no', models.CharField(default='주소', max_length=128)),
                ('dep_name', models.CharField(default='주소', max_length=128)),
                ('address', models.CharField(default='주소', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('rec_no', models.IntegerField(default=0)),
                ('avg_size', models.FloatField(default=0.0)),
                ('avg_x', models.FloatField(default=0.0)),
                ('avg_y', models.FloatField(default=0.0)),
                ('avg_speed', models.FloatField(default=0.0)),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all.Meta')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=128)),
                ('ext', models.CharField(default='확장자', max_length=32)),
                ('cctv', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cctv_videos', to='all.Cctv')),
            ],
        ),
        migrations.AddField(
            model_name='neighbor',
            name='spot1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spot1_neighbors', to='all.Spot'),
        ),
        migrations.AddField(
            model_name='neighbor',
            name='spot2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spot2_neighbors', to='all.Spot'),
        ),
        migrations.AddField(
            model_name='meta',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all.Video'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_cctvs', to='all.Manager'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='spots',
            field=models.ManyToManyField(blank=True, null=True, related_name='spot_cctvs', to='all.Spot'),
        ),
    ]
