# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctv',
            name='spots',
            field=models.ManyToManyField(blank=True, related_name='spot_cctvs', to='all.Spot'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='neighbors',
            field=models.ManyToManyField(blank=True, related_name='neighbor_seqs', to='all.Neighbor'),
        ),
    ]
