# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_auto_20171127_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
